
package package3;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Service3ImpService", targetNamespace = "http://package3/", wsdlLocation = "http://localhost:8080/service3/?wsdl")
public class Service3ImpService
    extends Service
{

    private final static URL SERVICE3IMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICE3IMPSERVICE_EXCEPTION;
    private final static QName SERVICE3IMPSERVICE_QNAME = new QName("http://package3/", "Service3ImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/service3/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICE3IMPSERVICE_WSDL_LOCATION = url;
        SERVICE3IMPSERVICE_EXCEPTION = e;
    }

    public Service3ImpService() {
        super(__getWsdlLocation(), SERVICE3IMPSERVICE_QNAME);
    }

    public Service3ImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICE3IMPSERVICE_QNAME, features);
    }

    public Service3ImpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE3IMPSERVICE_QNAME);
    }

    public Service3ImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE3IMPSERVICE_QNAME, features);
    }

    public Service3ImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Service3ImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Service3Interface
     */
    @WebEndpoint(name = "Service3ImpPort")
    public Service3Interface getService3ImpPort() {
        return super.getPort(new QName("http://package3/", "Service3ImpPort"), Service3Interface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Service3Interface
     */
    @WebEndpoint(name = "Service3ImpPort")
    public Service3Interface getService3ImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://package3/", "Service3ImpPort"), Service3Interface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICE3IMPSERVICE_EXCEPTION!= null) {
            throw SERVICE3IMPSERVICE_EXCEPTION;
        }
        return SERVICE3IMPSERVICE_WSDL_LOCATION;
    }

}
