
package package3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Service3Interface", targetNamespace = "http://package3/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Service3Interface {


    /**
     * 
     * @param getStudentAtIdId
     * @return
     *     returns package3.Student
     * @throws IOException_Exception
     * @throws JAXBException_Exception
     */
    @WebMethod
    @WebResult(name = "getStudentAtId", partName = "getStudentAtId")
    @Action(input = "http://package3/Service3Interface/getStudentAtIdRequest", output = "http://package3/Service3Interface/getStudentAtIdResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://package3/Service3Interface/getStudentAtId/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://package3/Service3Interface/getStudentAtId/Fault/IOException")
    })
    public Student getStudentAtId(
        @WebParam(name = "getStudentAtIdId", partName = "getStudentAtIdId")
        int getStudentAtIdId)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param checkIfIdHasStudentRoleId
     * @return
     *     returns boolean
     * @throws IOException_Exception
     * @throws JAXBException_Exception
     */
    @WebMethod
    @WebResult(name = "checkIfIdHasStudentRole", partName = "checkIfIdHasStudentRole")
    @Action(input = "http://package3/Service3Interface/checkIfIdHasStudentRoleRequest", output = "http://package3/Service3Interface/checkIfIdHasStudentRoleResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://package3/Service3Interface/checkIfIdHasStudentRole/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://package3/Service3Interface/checkIfIdHasStudentRole/Fault/IOException")
    })
    public boolean checkIfIdHasStudentRole(
        @WebParam(name = "checkIfIdHasStudentRoleId", partName = "checkIfIdHasStudentRoleId")
        int checkIfIdHasStudentRoleId)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param addModuleModuleCode
     * @param addModuleId
     * @param addModuleAy
     * @throws IOException_Exception
     * @throws JAXBException_Exception
     */
    @WebMethod
    @Action(input = "http://package3/Service3Interface/addModuleRequest", output = "http://package3/Service3Interface/addModuleResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://package3/Service3Interface/addModule/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://package3/Service3Interface/addModule/Fault/IOException")
    })
    public void addModule(
        @WebParam(name = "addModuleId", partName = "addModuleId")
        int addModuleId,
        @WebParam(name = "addModuleModuleCode", partName = "addModuleModuleCode")
        String addModuleModuleCode,
        @WebParam(name = "addModuleAy", partName = "addModuleAy")
        String addModuleAy)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param newMarkMc
     * @param newMarkId
     * @param newMarkay
     * @param newMarkMark
     * @return
     *     returns boolean
     * @throws IOException_Exception
     * @throws JAXBException_Exception
     */
    @WebMethod
    @WebResult(name = "newMark", partName = "newMark")
    @Action(input = "http://package3/Service3Interface/newMarkRequest", output = "http://package3/Service3Interface/newMarkResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://package3/Service3Interface/newMark/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://package3/Service3Interface/newMark/Fault/IOException")
    })
    public boolean newMark(
        @WebParam(name = "newMarkId", partName = "newMarkId")
        int newMarkId,
        @WebParam(name = "newMarkMc", partName = "newMarkMc")
        String newMarkMc,
        @WebParam(name = "newMarkay", partName = "newMarkay")
        String newMarkay,
        @WebParam(name = "newMarkMark", partName = "newMarkMark")
        double newMarkMark)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param reportMarkModuleCode
     * @param reportMarkId
     * @param reportMarkAy
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     * @throws JAXBException_Exception
     */
    @WebMethod
    @WebResult(name = "reportMark", partName = "reportMark")
    @Action(input = "http://package3/Service3Interface/reportMarkRequest", output = "http://package3/Service3Interface/reportMarkResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://package3/Service3Interface/reportMark/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://package3/Service3Interface/reportMark/Fault/IOException")
    })
    public String reportMark(
        @WebParam(name = "reportMarkId", partName = "reportMarkId")
        int reportMarkId,
        @WebParam(name = "reportMarkModuleCode", partName = "reportMarkModuleCode")
        String reportMarkModuleCode,
        @WebParam(name = "reportMarkAy", partName = "reportMarkAy")
        String reportMarkAy)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param getStudentsJaxb
     * @return
     *     returns package3.Students
     * @throws IOException_Exception
     * @throws JAXBException_Exception
     */
    @WebMethod
    @WebResult(name = "getStudents", partName = "getStudents")
    @Action(input = "http://package3/Service3Interface/getStudentsRequest", output = "http://package3/Service3Interface/getStudentsResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://package3/Service3Interface/getStudents/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://package3/Service3Interface/getStudents/Fault/IOException")
    })
    public Students getStudents(
        @WebParam(name = "getStudentsJaxb", partName = "getStudentsJaxb")
        JaxbContext getStudentsJaxb)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param addStudentId
     * @param addStudentStudent
     * @throws IOException_Exception
     * @throws JAXBException_Exception
     */
    @WebMethod
    @Action(input = "http://package3/Service3Interface/addStudentRequest", output = "http://package3/Service3Interface/addStudentResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://package3/Service3Interface/addStudent/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://package3/Service3Interface/addStudent/Fault/IOException")
    })
    public void addStudent(
        @WebParam(name = "addStudentStudent", partName = "addStudentStudent")
        Student addStudentStudent,
        @WebParam(name = "addStudentId", partName = "addStudentId")
        int addStudentId)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param saveStudentsJaxb
     * @param saveStudentsStudents
     * @throws IOException_Exception
     * @throws JAXBException_Exception
     */
    @WebMethod
    @Action(input = "http://package3/Service3Interface/saveStudentsRequest", output = "http://package3/Service3Interface/saveStudentsResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://package3/Service3Interface/saveStudents/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://package3/Service3Interface/saveStudents/Fault/IOException")
    })
    public void saveStudents(
        @WebParam(name = "saveStudentsStudents", partName = "saveStudentsStudents")
        Students saveStudentsStudents,
        @WebParam(name = "saveStudentsJaxb", partName = "saveStudentsJaxb")
        JaxbContext saveStudentsJaxb)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param getModuleId
     * @param getModuleAcdYear
     * @param getModuleModuleCode
     * @return
     *     returns package3.Module
     * @throws IOException_Exception
     * @throws JAXBException_Exception
     */
    @WebMethod
    @WebResult(name = "getModule", partName = "getModule")
    @Action(input = "http://package3/Service3Interface/getModuleRequest", output = "http://package3/Service3Interface/getModuleResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://package3/Service3Interface/getModule/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://package3/Service3Interface/getModule/Fault/IOException")
    })
    public Module getModule(
        @WebParam(name = "getModuleModuleCode", partName = "getModuleModuleCode")
        String getModuleModuleCode,
        @WebParam(name = "getModuleAcdYear", partName = "getModuleAcdYear")
        String getModuleAcdYear,
        @WebParam(name = "getModuleId", partName = "getModuleId")
        int getModuleId)
        throws IOException_Exception, JAXBException_Exception
    ;

}
