
package package2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Service2Interface", targetNamespace = "http://package2/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Service2Interface {


    /**
     * 
     * @param registrationOfEndUserId
     * @param registrationOfEndUserRole
     * @throws JAXBException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @Action(input = "http://package2/Service2Interface/registrationOfEndUserRequest", output = "http://package2/Service2Interface/registrationOfEndUserResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://package2/Service2Interface/registrationOfEndUser/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://package2/Service2Interface/registrationOfEndUser/Fault/IOException")
    })
    public void registrationOfEndUser(
        @WebParam(name = "registrationOfEndUserId", partName = "registrationOfEndUserId")
        int registrationOfEndUserId,
        @WebParam(name = "registrationOfEndUserRole", partName = "registrationOfEndUserRole")
        String registrationOfEndUserRole)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param enrollStudentOnModuleStudentId
     * @param enrollStudentOnModuleStudentAy
     * @param enrollStudentOnModuleStudentMc
     * @param enrollStudentOnModuleAsmId
     * @return
     *     returns int
     * @throws JAXBException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(name = "enrollStudentOnModule", partName = "enrollStudentOnModule")
    @Action(input = "http://package2/Service2Interface/enrollStudentOnModuleRequest", output = "http://package2/Service2Interface/enrollStudentOnModuleResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://package2/Service2Interface/enrollStudentOnModule/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://package2/Service2Interface/enrollStudentOnModule/Fault/IOException")
    })
    public int enrollStudentOnModule(
        @WebParam(name = "enrollStudentOnModuleAsmId", partName = "enrollStudentOnModuleAsmId")
        int enrollStudentOnModuleAsmId,
        @WebParam(name = "enrollStudentOnModuleStudentId", partName = "enrollStudentOnModuleStudentId")
        int enrollStudentOnModuleStudentId,
        @WebParam(name = "enrollStudentOnModuleStudentMc", partName = "enrollStudentOnModuleStudentMc")
        String enrollStudentOnModuleStudentMc,
        @WebParam(name = "enrollStudentOnModuleStudentAy", partName = "enrollStudentOnModuleStudentAy")
        String enrollStudentOnModuleStudentAy)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param reportingMarkForStudentStudentId
     * @param reportingMarkForStudentAcdYear
     * @param reportingMarkForStudentModuleCode
     * @param reportingMarkForStudentAsmId
     * @return
     *     returns java.lang.String
     * @throws JAXBException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(name = "reportingMarkForStudent", partName = "reportingMarkForStudent")
    @Action(input = "http://package2/Service2Interface/reportingMarkForStudentRequest", output = "http://package2/Service2Interface/reportingMarkForStudentResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://package2/Service2Interface/reportingMarkForStudent/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://package2/Service2Interface/reportingMarkForStudent/Fault/IOException")
    })
    public String reportingMarkForStudent(
        @WebParam(name = "reportingMarkForStudentAsmId", partName = "reportingMarkForStudentAsmId")
        int reportingMarkForStudentAsmId,
        @WebParam(name = "reportingMarkForStudentStudentId", partName = "reportingMarkForStudentStudentId")
        int reportingMarkForStudentStudentId,
        @WebParam(name = "reportingMarkForStudentModuleCode", partName = "reportingMarkForStudentModuleCode")
        String reportingMarkForStudentModuleCode,
        @WebParam(name = "reportingMarkForStudentAcdYear", partName = "reportingMarkForStudentAcdYear")
        String reportingMarkForStudentAcdYear)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param assignModuleToStaffMemberModuleCode
     * @param assignModuleToStaffMemberAsmId
     * @param assignModuleToStaffMemberId
     * @param assignModuleToStaffMemberAcdYear
     * @return
     *     returns int
     * @throws JAXBException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(name = "assignModuleToStaffMember", partName = "assignModuleToStaffMember")
    @Action(input = "http://package2/Service2Interface/assignModuleToStaffMemberRequest", output = "http://package2/Service2Interface/assignModuleToStaffMemberResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://package2/Service2Interface/assignModuleToStaffMember/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://package2/Service2Interface/assignModuleToStaffMember/Fault/IOException")
    })
    public int assignModuleToStaffMember(
        @WebParam(name = "assignModuleToStaffMemberId", partName = "assignModuleToStaffMemberId")
        int assignModuleToStaffMemberId,
        @WebParam(name = "assignModuleToStaffMemberModuleCode", partName = "assignModuleToStaffMemberModuleCode")
        String assignModuleToStaffMemberModuleCode,
        @WebParam(name = "assignModuleToStaffMemberAsmId", partName = "assignModuleToStaffMemberAsmId")
        int assignModuleToStaffMemberAsmId,
        @WebParam(name = "assignModuleToStaffMemberAcdYear", partName = "assignModuleToStaffMemberAcdYear")
        String assignModuleToStaffMemberAcdYear)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param insertNewMarkMarkAcdYear
     * @param insertNewMarkModuleCode
     * @param insertNewMarkMark
     * @param insertNewMarkAsmId
     * @param insertNewMarkStudentId
     * @return
     *     returns int
     * @throws JAXBException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(name = "insertNewMark", partName = "insertNewMark")
    @Action(input = "http://package2/Service2Interface/insertNewMarkRequest", output = "http://package2/Service2Interface/insertNewMarkResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://package2/Service2Interface/insertNewMark/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://package2/Service2Interface/insertNewMark/Fault/IOException")
    })
    public int insertNewMark(
        @WebParam(name = "insertNewMarkAsmId", partName = "insertNewMarkAsmId")
        int insertNewMarkAsmId,
        @WebParam(name = "insertNewMarkMark", partName = "insertNewMarkMark")
        double insertNewMarkMark,
        @WebParam(name = "insertNewMarkStudentId", partName = "insertNewMarkStudentId")
        int insertNewMarkStudentId,
        @WebParam(name = "insertNewMarkModuleCode", partName = "insertNewMarkModuleCode")
        String insertNewMarkModuleCode,
        @WebParam(name = "insertNewMarkMarkAcdYear", partName = "insertNewMarkMarkAcdYear")
        String insertNewMarkMarkAcdYear)
        throws IOException_Exception, JAXBException_Exception
    ;

}
