
package package1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Service1Interface", targetNamespace = "http://package1/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Service1Interface {


    /**
     * 
     * @param getAcademicStaffMembersJaxb
     * @return
     *     returns package1.AcademicStaffMembers
     * @throws JAXBException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(name = "getAcademicStaffMembers", partName = "getAcademicStaffMembers")
    @Action(input = "http://package1/Service1Interface/getAcademicStaffMembersRequest", output = "http://package1/Service1Interface/getAcademicStaffMembersResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://package1/Service1Interface/getAcademicStaffMembers/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://package1/Service1Interface/getAcademicStaffMembers/Fault/IOException")
    })
    public AcademicStaffMembers getAcademicStaffMembers(
        @WebParam(name = "getAcademicStaffMembersJaxb", partName = "getAcademicStaffMembersJaxb")
        JaxbContext getAcademicStaffMembersJaxb)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param saveAcademicStaffMembersAcademicStaffMembers
     * @param saveAcademicStaffMembersJaxb
     * @throws JAXBException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @Action(input = "http://package1/Service1Interface/saveAcademicStaffMembersRequest", output = "http://package1/Service1Interface/saveAcademicStaffMembersResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://package1/Service1Interface/saveAcademicStaffMembers/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://package1/Service1Interface/saveAcademicStaffMembers/Fault/IOException")
    })
    public void saveAcademicStaffMembers(
        @WebParam(name = "saveAcademicStaffMembersAcademicStaffMembers", partName = "saveAcademicStaffMembersAcademicStaffMembers")
        AcademicStaffMembers saveAcademicStaffMembersAcademicStaffMembers,
        @WebParam(name = "saveAcademicStaffMembersJaxb", partName = "saveAcademicStaffMembersJaxb")
        JaxbContext saveAcademicStaffMembersJaxb)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param getAcademicStaffMemberAtIdId
     * @return
     *     returns package1.AcademicStaffMember
     * @throws JAXBException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(name = "getAcademicStaffMemberAtId", partName = "getAcademicStaffMemberAtId")
    @Action(input = "http://package1/Service1Interface/getAcademicStaffMemberAtIdRequest", output = "http://package1/Service1Interface/getAcademicStaffMemberAtIdResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://package1/Service1Interface/getAcademicStaffMemberAtId/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://package1/Service1Interface/getAcademicStaffMemberAtId/Fault/IOException")
    })
    public AcademicStaffMember getAcademicStaffMemberAtId(
        @WebParam(name = "getAcademicStaffMemberAtIdId", partName = "getAcademicStaffMemberAtIdId")
        int getAcademicStaffMemberAtIdId)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param checkIfIdHasACDRole
     * @return
     *     returns boolean
     * @throws JAXBException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(name = "checkIfIdHasACDRole", partName = "checkIfIdHasACDRole")
    @Action(input = "http://package1/Service1Interface/checkIfIdHasACDRoleRequest", output = "http://package1/Service1Interface/checkIfIdHasACDRoleResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://package1/Service1Interface/checkIfIdHasACDRole/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://package1/Service1Interface/checkIfIdHasACDRole/Fault/IOException")
    })
    public boolean checkIfIdHasACDRole(
        @WebParam(name = "checkIfIdHasACDRole", partName = "checkIfIdHasACDRole")
        int checkIfIdHasACDRole)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param addAcademicStaffMemberAcademicStaffMember
     * @param addAcademicStaffMemberId
     * @throws JAXBException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @Action(input = "http://package1/Service1Interface/addAcademicStaffMemberRequest", output = "http://package1/Service1Interface/addAcademicStaffMemberResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://package1/Service1Interface/addAcademicStaffMember/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://package1/Service1Interface/addAcademicStaffMember/Fault/IOException")
    })
    public void addAcademicStaffMember(
        @WebParam(name = "addAcademicStaffMemberAcademicStaffMember", partName = "addAcademicStaffMemberAcademicStaffMember")
        AcademicStaffMember addAcademicStaffMemberAcademicStaffMember,
        @WebParam(name = "addAcademicStaffMemberId", partName = "addAcademicStaffMemberId")
        int addAcademicStaffMemberId)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param addModule1Ay
     * @param addModule1ModuleCode
     * @param addModule1Id
     * @throws JAXBException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @Action(input = "http://package1/Service1Interface/addModule1Request", output = "http://package1/Service1Interface/addModule1Response", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://package1/Service1Interface/addModule1/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://package1/Service1Interface/addModule1/Fault/IOException")
    })
    public void addModule1(
        @WebParam(name = "addModule1Id", partName = "addModule1Id")
        int addModule1Id,
        @WebParam(name = "addModule1ModuleCode", partName = "addModule1ModuleCode")
        String addModule1ModuleCode,
        @WebParam(name = "addModule1Ay", partName = "addModule1Ay")
        String addModule1Ay)
        throws IOException_Exception, JAXBException_Exception
    ;

    /**
     * 
     * @param getModule1AcdYear
     * @param getModule1Id
     * @param getModule1Module1Code
     * @return
     *     returns package1.Module1
     * @throws JAXBException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(name = "getModule1", partName = "getModule1")
    @Action(input = "http://package1/Service1Interface/getModule1Request", output = "http://package1/Service1Interface/getModule1Response", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://package1/Service1Interface/getModule1/Fault/JAXBException"),
        @FaultAction(className = IOException_Exception.class, value = "http://package1/Service1Interface/getModule1/Fault/IOException")
    })
    public Module1 getModule1(
        @WebParam(name = "getModule1Module1Code", partName = "getModule1Module1Code")
        String getModule1Module1Code,
        @WebParam(name = "getModule1AcdYear", partName = "getModule1AcdYear")
        String getModule1AcdYear,
        @WebParam(name = "getModule1Id", partName = "getModule1Id")
        int getModule1Id)
        throws IOException_Exception, JAXBException_Exception
    ;

}
